# Generated by Django 4.2.10 on 2024-03-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_book_quantity_alter_book_author_alter_book_available_and_more'),
        ('user', '0002_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_products',
            field=models.ManyToManyField(related_name='users_who_favorited', to='store.book', verbose_name='Избранное'),
        ),
    ]
