# Generated by Django 4.2.10 on 2024-03-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_amount_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Общая сумма заказа'),
        ),
    ]
